### ISSUE TITLE
Bot is faster than actual player

### ISSUE THREAD

**Issue by bsteps** [asif987patel/material#4]
when I was playing the game bot felt like it was moving a lot faster than me. i think you should make its speed same a player. what do you say

**Comment by mazimez** [comment]
Thanks for your feedback, I actually thought of making the BOT(ghost) slow  or same speed as the player at first level and then increase it a little with level. But that mechanism is not working properly. It does make BOT(ghost)  slower at first level but as level increases, the BOT(ghost) gets too fast.

I will surely fix this and update the game as soon as possible. 
again thanks for your Feedback

**Comment by mazimez** [comment]
@bsteps, I have updated the Ghost Speed to be very slow at start and increase with level, hope you like it.
